some optimizes

diff --git a/.github/workflows/check-license-header.yml b/.github/workflows/check-license-header.yml
--- a/.github/workflows/check-license-header.yml
+++ b/.github/workflows/check-license-header.yml
@@ -24,15 +24,29 @@ jobs:
         run: |
           current_year=$(date +"%Y")  # Dynamically set current year for checking
           echo "current_year=$current_year" >> $GITHUB_ENV  # Export current year to environment variables
+
           missing_license_files=""
           for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
             # Check if file contains the correct SPDX license identifier and the exact copyright statement with dynamic current year
             if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file" || ! grep -q "SPDX-FileCopyrightText: © $current_year Tenstorrent AI ULC" "$file"; then
-              missing_license_files="$missing_license_files$file "
+              missing_license_files="${missing_license_files}${file}\n"
             fi
           done
-          echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV
+
+          # Remove trailing newline character
+          missing_license_files=$(echo -e "$missing_license_files" | sed '/^\s*$/d')
+          echo "missing_license_files<<EOF" >> $GITHUB_ENV
+          echo -e "$missing_license_files" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
           echo "Checked files for correct SPDX-License compliance."
+          
+          if [ -n "$missing_license_files" ]; then
+            echo "Files with missing or incorrect SPDX license headers found:\n$missing_license_files"
+            exit 1
+          else
+            echo "No issues found with SPDX license headers."
+          fi
 
       - name: Comment on PR about incorrect SPDX licenses
         if: env.missing_license_files != ''
@@ -45,7 +59,7 @@ jobs:
             const missingFiles = process.env.missing_license_files.trim().replace(/\s+/g, '\n');
             const currentYear = process.env.current_year;
             const commentBody = `The following files are not compliant with the required licensing standards for ${currentYear} or do not contain the correct copyright text 'Tenstorrent AI ULC' within their license header:\n\`\`\`\n${missingFiles}\n\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\nThank you.`;
-            
+
             github.rest.issues.createComment({
               issue_number: issueNumber,
               owner: owner,
