try again

diff --git a/.github/workflows/liscense-checker.yml b/.github/workflows/liscense-checker.yml
--- a/.github/workflows/liscense-checker.yml
+++ b/.github/workflows/liscense-checker.yml
@@ -1,9 +1,8 @@
-name: "Check if License is present"
+name: Validate SPDX License year and company mention in currently changed Files
 
 on:
   pull_request:
-    branches:
-      - "main"
+    branches: [main]
     types:
       - opened
       - reopened
@@ -12,11 +11,13 @@ on:
       - review_requested
 
 jobs:
-  check-license-headers-on-pr:
-    runs-on: ubuntu-20.04
+  check-spdx-license:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 2
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -26,36 +27,52 @@ jobs:
       - name: Install Check-copyright
         run: python -m pip install git+https://github.com/espressif/check-copyright.git@master
 
-      - name: Check SPDX licenses and comment on PR, then fail if issues found
+      - name: Identify currently changed files and check licenses
+        id: check-licenses
+        run: |
+          current_year=$(date +"%Y")
+          echo "current_year=$current_year" >> $GITHUB_ENV
+
+          missing_license_files=""
+          for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
+            # Check if file contains the correct SPDX license identifier and the exact copyright statement with dynamic current year
+            if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file" || ! grep -q "SPDX-FileCopyrightText: © $current_year Tenstorrent AI ULC" "$file"; then
+              missing_license_files="${missing_license_files}${file}\n"
+            fi
+          done
+
+          # Remove trailing newline character
+          missing_license_files=$(echo -e "$missing_license_files" | sed '/^\s*$/d')
+          echo "missing_license_files<<EOF" >> $GITHUB_ENV
+          echo -e "$missing_license_files" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          if [ -n "$missing_license_files" ]; then
+            echo "Files with missing or incorrect SPDX license headers found:\n$missing_license_files"
+            exit 1
+          else
+            echo "No issues found with SPDX license headers."
+          fi
+
+      - name: Comment on PR about incorrect SPDX licenses
+        if: env.missing_license_files != ''
         uses: actions/github-script@v6
         with:
           script: |
-            const execSync = require('child_process').execSync;
-            const command = `python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml . | awk '/Some files are without a copyright note and a license header needs to be added:/{flag=1; next} /Additional information about this hook and copyright headers may be found here:/{flag=0} flag'`;
-            let output;
-            try {
-              output = execSync(command, { encoding: 'utf-8' }); // captures stdout
-            } catch (error) {
-              output = error.stdout; // captures stdout from the error, if command execution fails
-            }
+            const { issue, repo } = context;
+            const missingFiles = process.env.missing_license_files.trim().replace(/\s+/g, '\n');
+            const currentYear = process.env.current_year;
+            const commentBody = `The following files are not compliant with the required licensing standards for ${currentYear} or do not contain the correct copyright text 'Tenstorrent AI ULC' within their license header:\n\`\`\`\n${missingFiles}\n\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\nThank you.`;
 
-            // Remove ANSI color codes and prepare the output
-            output = output.replace(/\u001b\[.*?m/g, '');
-            const formattedOutput = output.split('\n').filter(line => line.trim() !== '').map(line => `- ${line}`).join('\n');
+            github.rest.issues.createComment({
+              issue_number: issue.number,
+              owner: repo.owner,
+              repo: repo.repo,
+              body: commentBody
+            });
 
-            const issueNumber = context.issue.number;
-            const owner = context.repo.owner;
-            const repo = context.repo.repo;
-
-            if (formattedOutput) {
-              const commentBody = `Our automated SPDX license verification process has discovered that the following files are missing a license header:\n\`\`\`\n${formattedOutput}\n\`\`\`\nPlease ensure each indicated file includes a valid SPDX license identifier. This is essential for maintaining licensing compliance. Your attention and cooperation in updating these files are greatly appreciated. Thank you.`;
-              await github.rest.issues.createComment({
-                issue_number: issueNumber,
-                owner: owner,
-                repo: repo,
-                body: commentBody
-              });
-              core.setFailed("SPDX license issues found.");
-            } else {
-              console.log("No SPDX license issues found.");
-            }
+      - name: Fail the workflow if license issues are found
+        if: env.missing_license_files != ''
+        run: |
+          echo "Failing the workflow due to non-compliance with SPDX license requirements."
+          exit 1
